### ISSUE TITLE
Offset issue appearing in an analysis_options.yaml file

### ISSUE THREAD

**Issue by jwren** [dart-lang/yaml#89] opened 2020-09-21 20:29 UTC
Offset issue appearing in `2020.2 EAP` version of IJ:

![Screen Shot 2020-09-21 at 1 24 10 PM](https://user-images.githubusercontent.com/1533520/93817846-61df7e80-fc0e-11ea-8e34-87073224061a.png)

**Comment by bwilkerson** [comment] 2020-10-04 18:01
I looked at the parser and didn't see any obvious problem, so I looked at the analyzer's use of the parser and believe that I have found the problem (https://dart-review.googlesource.com/c/sdk/+/165980). The issue isn't in the parser, so I'm closing this issue.

**Closed by bwilkerson** 2020-10-04 18:01 UTC
Labels: bug
